- obs space:
    name: ahi_himawari8
    obsdatain:
      obsfile: InDBDir/ahi_himawari8_obs_2018041500.h5
    obsdataout:
      obsfile: OutDBDirOOPSMemberDir/obsPrefix_AppType_ahi_himawari8.h5
    simulated variables: [brightness_temperature]
    channels: &ahi_channels 8-10
    obs perturbations seed: MemberSeed
  obs operator:
    name: CRTM
    SurfaceWindGeoVars: uv
    Absorbers: [H2O,O3,CO2]
    Clouds: [Water, Ice, Rain, Snow, Graupel]
    linear obs operator:
      Absorbers: [H2O]
      Clouds: [Water, Ice, Rain, Snow, Graupel]
    obs options:
      Sensor_ID: ahi_himawari8
      EndianType: little_endian
      CoefficientPath: CRTMTABLES
      IRVISlandCoeff: USGS
  obs error:
    covariance model: diagonal
  obs filters:
  - filter: Domain Check
    where:
    - variable:
        name: sensor_zenith_angle@MetaData
      maxvalue: 65.0
    apply at iterations: 0, 1
#  - filter: Thinning
#    amount: RADTHINAMOUNT
#    random_seed: 0
  - filter: Gaussian_Thinning
    horizontal_mesh: RADTHINDISTANCE #km
  - filter: BlackList
    apply at iterations: 0, 1
    filter variables:
    - name: brightness_temperature
      channels: *ahi_channels
#  - filter: Domain Check
#    where:
#    - variable:
#        name: cloud_area_fraction@MetaData
#      minvalue: 0.05
    action:
      name: assign error
      error function:
        name: ObsErrorModelRamp@ObsFunction
        channels: *ahi_channels
        options:
          channels: *ahi_channels
          xvar:
            name: SymmCldImpactIR@ObsFunction
            channels: *ahi_channels
            options:
              channels: *ahi_channels
## 120 km, no bias correction
          x0: [1, 1, 1]
          x1: [12.27, 15.52, 22.96]
          err0: [1.96, 1.95, 2.62]
          err1: [13.1, 15.51, 17.16]
  - filter: Background Check
    threshold: 3.0
    apply at iterations: 0, 1
  - filter: GOMsaver
    filename: OutDBDirOOPSMemberDir/geoPrefix_AppType_ahi_himawari8.nc4
  - filter: YDIAGsaver
    filename: OutDBDirOOPSMemberDir/diagPrefix_AppType_ahi_himawari8.nc4
    filter variables:
    - name: brightness_temperature_assuming_clear_sky
      channels: *ahi_channels
    - name: weightingfunction_of_atmosphere_layer
      channels: *ahi_channels
    - name: pressure_level_at_peak_of_weightingfunction
      channels: *ahi_channels
    - name: brightness_temperature_jacobian_air_temperature
      channels: *ahi_channels
    - name: brightness_temperature_jacobian_humidity_mixing_ratio
      channels: *ahi_channels
    - name: brightness_temperature_jacobian_surface_emissivity
      channels: *ahi_channels
    - name: brightness_temperature_jacobian_surface_temperature
      channels: *ahi_channels
  get values:
    interpolation type: InterpolationType
