- obs space:
    name: abi_g16
    obsdatain:
      obsfile: InDBDir/abi_g16_obs_2018041500.h5
    obsdataout:
      obsfile: OutDBDirOOPSMemberDir/obsPrefix_AppType_abi_g16.h5
    simulated variables: [brightness_temperature]
    channels: &abi_channels 8-10
#    channels: &abi_channels 8-10,13-16
#    channels: &abi_channels 7-11,13-16
    obs perturbations seed: MemberSeed
  obs operator:
    name: CRTM
    SurfaceWindGeoVars: uv
    Absorbers: [H2O,O3,CO2]
    Clouds: [Water, Ice, Rain, Snow, Graupel]
    linear obs operator:
      Absorbers: [H2O]
      Clouds: [Water, Ice, Rain, Snow, Graupel]
    obs options:
      Sensor_ID: abi_g16
      EndianType: little_endian
      CoefficientPath: CRTMTABLES
      IRVISlandCoeff: USGS
  obs error:
    covariance model: diagonal
  obs filters:
  - filter: Domain Check
    where:
    - variable:
        name: sensor_zenith_angle@MetaData
      maxvalue: 65.0
#    - variable:
#        name: water_area_fraction@GeoVaLs
#      minvalue: 1.0
    apply at iterations: 0, 1
#  - filter: Thinning
#    amount: RADTHINAMOUNT
#    random_seed: 0
#    apply at iterations: 0
  - filter: Gaussian_Thinning
    horizontal_mesh: RADTHINDISTANCE #km
  - filter: BlackList
    apply at iterations: 0, 1
    filter variables:
    - name: brightness_temperature
      channels: *abi_channels
#  - filter: Domain Check
#    where:
#    - variable:
#        name: cloud_area_fraction@MetaData
#      minvalue: 0.05
    action:
      name: assign error
      error function:
        name: ObsErrorModelRamp@ObsFunction
        channels: *abi_channels
        options:
          channels: *abi_channels
          xvar:
            name: SymmCldImpactIR@ObsFunction
            channels: *abi_channels
            options:
              channels: *abi_channels
## 120 km, w/ bias correction
#          x0: []
#          x1: []
#          err0: []
#          err1: []
## 120 km, no bias correction
          x0: [1.0, 1.0, 1.0]
          x1: [14.28, 17.89, 20.3]
          err0: [1.86, 1.84, 2.24]
          err1: [16.95, 19.67, 18.51]
#deflate30%
#          err1: [11.87, 13.77, 12.96]
  - filter: Background Check
    threshold: 3.0
    apply at iterations: 0, 1
## Ignore cloud-affected pixels in 1st iteration
#  - filter: Domain Check
#    apply at iterations: 0
#    filter variables:
#    - name: brightness_temperature
#      channels: *abi_channels
#    where:
#    - variable:
##        name: cloud_area_fraction@MetaData
#        name: SymmCldImpactIR@ObsFunction
#        channels: *abi_channels
#        options:
#          channels: *abi_channels
#      maxvalue: 0.01
#    action:
#      name: assign error
#      error parameter: 1000.0
  - filter: GOMsaver
    filename: OutDBDirOOPSMemberDir/geoPrefix_AppType_abi_g16.nc4
  - filter: YDIAGsaver
    filename: OutDBDirOOPSMemberDir/diagPrefix_AppType_abi_g16.nc4
    filter variables:
    - name: brightness_temperature_assuming_clear_sky
      channels: *abi_channels
    - name: weightingfunction_of_atmosphere_layer
      channels: *abi_channels
    - name: pressure_level_at_peak_of_weightingfunction
      channels: *abi_channels
    - name: brightness_temperature_jacobian_air_temperature
      channels: *abi_channels
    - name: brightness_temperature_jacobian_humidity_mixing_ratio
      channels: *abi_channels
    - name: brightness_temperature_jacobian_surface_emissivity
      channels: *abi_channels
    - name: brightness_temperature_jacobian_surface_temperature
      channels: *abi_channels
  get values:
    interpolation type: InterpolationType
