- obs space:
    name: ahi-clr_himawari8
    obsdatain:
      obsfile: InDBDir/ahi_himawari8_obs_2018041500.h5
    obsdataout:
      obsfile: OutDBDirOOPSMemberDir/obsPrefix_AppType_ahi_himawari8.h5
    simulated variables: [brightness_temperature]
    channels: &clrahi_channels 7-16
    obs perturbations seed: MemberSeed
  obs operator:
    name: CRTM
    SurfaceWindGeoVars: uv
    Absorbers: [H2O,O3,CO2]
    linear obs operator:
      Absorbers: [H2O]
    obs options:
      Sensor_ID: ahi_himawari8
      EndianType: little_endian
      CoefficientPath: CRTMTABLES
      IRVISlandCoeff: USGS
  obs error:
    covariance model: diagonal
  obs filters:
  - filter: Domain Check
    where:
    - variable:
        name: sensor_zenith_angle@MetaData
      maxvalue: 65.0
    - variable:
        name: cloud_area_fraction@MetaData
      maxvalue: 0.05
    apply at iterations: 0, 1
  - filter: Background Check
    threshold: 3.0
    apply at iterations: 0, 1
  - filter: GOMsaver
    filename: OutDBDirOOPSMemberDir/geoPrefix_AppType_ahi_himawari8.nc4
  - filter: YDIAGsaver
    filename: OutDBDirOOPSMemberDir/diagPrefix_AppType_ahi_himawari8.nc4
    filter variables:
    - name: brightness_temperature_assuming_clear_sky
      channels: *clrahi_channels
    - name: weightingfunction_of_atmosphere_layer
      channels: *clrahi_channels
    - name: pressure_level_at_peak_of_weightingfunction
      channels: *clrahi_channels
    - name: brightness_temperature_jacobian_air_temperature
      channels: *clrahi_channels
    - name: brightness_temperature_jacobian_humidity_mixing_ratio
      channels: *clrahi_channels
    - name: brightness_temperature_jacobian_surface_emissivity
      channels: *clrahi_channels
    - name: brightness_temperature_jacobian_surface_temperature
      channels: *clrahi_channels
  get values:
    interpolation type: InterpolationType
